# Generated by Django 3.2.18 on 2023-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Minh Le', max_length=255),
            preserve_default=False,
        ),
    ]
